version: "3.7"

services:
  app:
    container_name: app
    image: app_image
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    depends_on:
      - app_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
    networks:
      - app_network

  app_db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d/

  app_redis:
    image: redis:6.2-alpine
    hostname: redis
    restart: unless-stopped
    container_name: app_redis
    command:
      - "redis-server"
      - "--requirepass $REDIS_PASSWORD"
    ports:
      - 6379:6379
    networks:
      - app_network

volumes:
  db:
    driver: "local"

networks:
  app_network:
    driver: bridge
