"""2. add user aliasy

Revision ID: 23a75af772b7
Revises: 6a5bf5a94ce9
Create Date: 2023-08-11 13:12:32.268087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a75af772b7'
down_revision: Union[str, None] = '6a5bf5a94ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alias', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alias')
    # ### end Alembic commands ###
