"""4. remove relationship

Revision ID: 2cf20b052545
Revises: 99c1cd43688e
Create Date: 2023-08-11 21:02:21.768611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2cf20b052545'
down_revision: Union[str, None] = '99c1cd43688e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'release_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('release_date', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
