"""1. remove play_history and add lastplay

Revision ID: 6a5bf5a94ce9
Revises: 7a60f44fb5d8
Create Date: 2023-08-11 13:02:34.427610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a5bf5a94ce9'
down_revision: Union[str, None] = '7a60f44fb5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('play_history')
    op.add_column('users', sa.Column('last_play_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('users_last_play_id_fkey'), 'users', 'songs', ['last_play_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_last_play_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'last_play_id')
    op.create_table('play_history',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('song_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name='play_history_song_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='play_history_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'song_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
