"""0.initial tables and relationship

Revision ID: 7a60f44fb5d8
Revises: 
Create Date: 2023-08-09 21:04:21.314929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a60f44fb5d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('artists_pkey'))
    )
    op.create_index(op.f('artists_id_idx'), 'artists', ['id'], unique=False)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('songs_pkey'))
    )
    op.create_index(op.f('songs_id_idx'), 'songs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=True)
    op.create_index(op.f('users_id_idx'), 'users', ['id'], unique=False)
    op.create_index(op.f('users_username_idx'), 'users', ['username'], unique=False)
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=255), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('albums_artist_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('albums_pkey'))
    )
    op.create_index(op.f('albums_id_idx'), 'albums', ['id'], unique=False)
    op.create_table('play_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('play_history_song_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('play_history_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'song_id', name=op.f('play_history_pkey'))
    )
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('playlists_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('playlists_pkey'))
    )
    op.create_index(op.f('playlists_id_idx'), 'playlists', ['id'], unique=False)
    op.create_table('song_artists',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('song_artists_artist_id_fkey')),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('song_artists_song_id_fkey')),
    sa.PrimaryKeyConstraint('song_id', 'artist_id', name=op.f('song_artists_pkey'))
    )
    op.create_table('user_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('user_favorites_song_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_favorites_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'song_id', name=op.f('user_favorites_pkey'))
    )
    op.create_table('playlist_songs',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('playlist_songs_playlist_id_fkey')),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('playlist_songs_song_id_fkey')),
    sa.PrimaryKeyConstraint('playlist_id', 'song_id', name=op.f('playlist_songs_pkey'))
    )
    op.create_table('song_albums',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('song_albums_album_id_fkey')),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('song_albums_song_id_fkey')),
    sa.PrimaryKeyConstraint('song_id', 'album_id', name=op.f('song_albums_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_albums')
    op.drop_table('playlist_songs')
    op.drop_table('user_favorites')
    op.drop_table('song_artists')
    op.drop_index(op.f('playlists_id_idx'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_table('play_history')
    op.drop_index(op.f('albums_id_idx'), table_name='albums')
    op.drop_table('albums')
    op.drop_index(op.f('users_username_idx'), table_name='users')
    op.drop_index(op.f('users_id_idx'), table_name='users')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('songs_id_idx'), table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('artists_id_idx'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
